export * from "./user.interface";
export * from "./gym.interface";
export * from "./session.interface";
export * from "./exercise.interface";
export * from "./typeExercise.interface";
export * from "./badge.interface";
export * from "./challenge.interface";
export * from "./participation.interface";
export * from "./timestamps";